USE organeyez_db;
SELECT * FROM protests;
SELECT * FROM events;
SELECT * FROM dates;
SELECT * FROM stories;
SELECT * FROM vitalInfo;
SELECT * FROM localOfficials;
SELECT * FROM businesses;
SELECT * FROM donations;
SELECT * FROM petitions;